# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: master

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# search for requirement files
# default: True
# allowed: True, False
search: True

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
  - requirements.txt:
      update: all
      pin: True
  - readthedocs-environment.yml:
      # update all dependencies and pin them
      update: all
      pin: True
  - environment.yml:
      # don't update dependencies, use global 'pin' default
      update: all
      pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: requirements_version

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
 - nrweir

# configure the branch prefix the bot is using
# default: pyup-

# set a global prefix for PRs
# default: empty
pr_prefix: "Requirements:"

# allow to close stale PRs
# default: True
close_prs: True
