name: Test Python package

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Docker | GDAL=${{ matrix.gdal-version }} | python=${{ matrix.python-version }}
    container: osgeo/gdal:ubuntu-small-${{ matrix.gdal-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        gdal-version: ["3.4.0", "3.3.3"]
        include:
          - python-version: "3.8"
            gdal-version: "3.2.3"
          - python-version: "3.8"
            gdal-version: "3.1.3"
          - python-version: "3.7"
            gdal-version: "3.2.3"
          - python-version: "3.7"
            gdal-version: "3.1.3"

    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: |
          apt-get update
          apt-get -y install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get update
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          apt-get install -y --no-install-recommends \
            python${{ matrix.python-version }} \
            python${{ matrix.python-version }}-dev \
            python${{ matrix.python-version }}-venv \
            python3-pip \
            g++ \
            libgl1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Lint with tox
        run: tox -e lint
      - name: Format with tox
        run: tox -e format
      - name: Test with tox
        run: tox -e test

